"""new data model

Revision ID: 85a923a00e3a
Revises: e6d63b5908bc
Create Date: 2024-12-08 15:22:30.226593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a923a00e3a'
down_revision = 'e6d63b5908bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_index('ix_data_name')

    op.drop_table('data')
    with op.batch_alter_table('users', schema=None) as batch_op:
       batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
       batch_op.alter_column('username',
              existing_type=sa.VARCHAR(length=100),
              nullable=False)
       batch_op.alter_column('email',
              existing_type=sa.VARCHAR(length=200),
              nullable=False)
       batch_op.alter_column('password_hash',
              existing_type=sa.VARCHAR(length=128),
              nullable=False)
       batch_op.drop_index('ix_users_email')
       batch_op.drop_index('ix_users_username')
       batch_op.create_unique_constraint('uq_users_username', ['username'])
       batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
       batch_op.drop_constraint('uq_users_username', type_='unique')
       batch_op.drop_constraint('uq_users_email', type_='unique')
       batch_op.create_index('ix_users_username', ['username'], unique=1)
       batch_op.create_index('ix_users_email', ['email'], unique=1)
       batch_op.alter_column('password_hash',
              existing_type=sa.VARCHAR(length=128),
              nullable=True)
       batch_op.alter_column('email',
              existing_type=sa.VARCHAR(length=200),
              nullable=True)
       batch_op.alter_column('username',
              existing_type=sa.VARCHAR(length=100),
              nullable=True)
       batch_op.drop_column('created_at')

    op.create_table('data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=False),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.create_index('ix_data_name', ['name'], unique=1)

    op.drop_table('user_products')
    op.drop_table('products')
    op.drop_table('categories')
    # ### end Alembic commands ###
